name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -U postgres -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      # Passo para instalar o dockerize
      - name: Install dockerize
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
          tar -xvzf dockerize-linux-amd64-v0.6.1.tar.gz
          sudo mv dockerize /usr/local/bin
          dockerize --version  # Verificar se o dockerize foi instalado corretamente

      - name: Wait for PostgreSQL to be ready
        run: |
          dockerize -wait tcp://localhost:5432 -timeout 1m

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: password
          DB_NAME: test_db
        run: |
          npm run test
